language: java
dist: bionic
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2/repository"
sudo: false
env:
  global:
    - ORG="devonfw-forge"
    - EMAIL="icsddevonfwsupport.apps2@capgemini.com"
    - REPO_SOURCE="bpm"
    - REPO_DEST="bpm.wiki"
    - REPO_CONSOLIDATE="devonfw-guide"
    - GH_REPO_DEST="github.com/${ORG}/${REPO_DEST}.git"
install: skip
stages:
  - name: Build
  - name: Documentation
jobs:
  include:
    - stage: Build
      script:
        - mvn install
    - stage: Documentation
      if: (branch = master) AND (type = push)
      script:
        # Exit devon4j folder
        - cd ..
        # Clone repositories
        - git clone https://${GH_REPO_DEST}
        # Update wiki repository with documentation folder contents
        - yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
        - cd ${REPO_DEST}
        - grep -lr "link:[a-zA-Z0-9_.-]*.asciidoc.*" .| xargs -r sed -i "s/.asciidoc//g"
        # Terminate Travis CI build when no changes detected
        - |
          if git diff-index --quiet HEAD && [ ! -n "$(git status -s)" ]; then 
            set +e 
            pkill -9 -P $$ &> /dev/null || true 
            exit 0
          else 
            git config user.email ${EMAIL}
            git config user.name ${USER}
            git status
            git add .
            git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
            git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_DEST}"
            git push origin-wiki master
          fi
